name = "glector"
version = "1.1.0"

description = "2D vectors for Gleam"
licences = ["Apache-2.0"]
repository = { type = "github", user = "0xca551e", repo = "glector" }
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = ">= 0.34.0 and < 2.0.0"

[dev-dependencies]
startest = ">= 0.2.0 and < 1.0.0"
